#!/usr/bin/env python3
"""0-list_databases"""
from pymongo import MongoClient


# Connect to MongoDB
client = MongoClient('mongodb://localhost:27017/')

# List all databases
db_names = client.list_database_names()

# Print the list of databases
print("Databases:")
for db_name in db_names:
    print(db_name)
