#!/usr/bin/env python3
"""0-list_databases"""
from pymongo import MongoClient


# Connect to MongoDB
client = MongoClient('mongodb://localhost:27017/')

# List all databases
db_info = client.admin.command('listDatabases')

# Print the list of databases
for db in db_info['databases']:
    print(db['name'], "\t", db['sizeOnDisk'])
